# Generated by Django 4.1.6 on 2023-02-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='categorie/', verbose_name="image representative d'une categorie")),
            ],
        ),
    ]
