# Generated by Django 4.1.6 on 2023-02-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('image1', models.ImageField(upload_to='articles/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.categorie')),
            ],
        ),
    ]
