# Generated by Django 4.1.6 on 2023-02-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0004_alter_promotion_pourcent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description de la promotion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.article', verbose_name='produit associer'),
        ),
    ]
