# Generated by Django 4.1.6 on 2023-02-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0005_alter_promotion_description_alter_promotion_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
