# Generated by Django 4.1.6 on 2023-02-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0008_promotion_date_de_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-date_de_creation']},
        ),
    ]
