# Generated by Django 4.1.6 on 2023-02-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0009_alter_promotion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['date_de_creation']},
        ),
    ]
