# Generated by Django 4.1.6 on 2023-02-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0010_alter_promotion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date_de_creation',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
