# Generated by Django 4.1.6 on 2023-02-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0012_alter_promotion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_creation']},
        ),
    ]
