# Generated by Django 4.1.6 on 2023-03-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0013_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_site', models.CharField(default='copkin', editable=False, max_length=30)),
                ('numero_whatsapp', models.CharField(default='243850411990', help_text=' ex : 24398765795 (Sans espace ni +', max_length=16)),
                ('autre_numero', models.CharField(default='243850411990', help_text=' ex : 24398765795 (Sans espace ni +', max_length=16)),
                ('adresse', models.CharField(default='ville de kinshasa', max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
